# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85bf9523648dbc63b1f59f81a931ae9388f9b0a03642145d1be37609b34cd26332118a8cc76efc9b7b0a964cf6273fa66197a92866b650d01293ee7edf32f4aa

test:
  secret_key_base: c704fcf0eb35312c2c1b35178bd8f6d4b9ba4af725157789fc1f55b57fd6eb5a26b36df34868eec37333c38668e2fee0dd5ad8d401ed88da6c4a2d512f4d8405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
